### ISSUE TITLE
consider pulling from flipper-irdb instead of the older irdb?

### ISSUE THREAD

**Issue by psifertex** [geo-tp/Ultimate-Remote#1]
The latest flipper IRDB has a nicely organized repo and it seems to have a much lager and broader collection of devices:

https://github.com/Lucaslhm/Flipper-IRDB

The only problem would be deconflicting/integrating which would be rather annoying given naming conventions being different. Given how much more robust the flipper DB is, it might make sense to just swap out for it wholesale. 

The file format being off looks pretty simple to convert as well.

**Comment by geo-tp** [comment]
Hi,

I didn't know that flipper had an IR database, indeed it would definitely be best to have both databases together on one firmware, but that could be a lot of parsing work.

Since Flipper already uses this database, it might be a good idea to keep a whole other IR database that could include other remotes as IRDB maybe.

I will try to see if I can parse the Flipper remotes into IRDB format to allow the existing logic to be used.

Thank you for notifying me of the existence of the flipper IRDB

**Comment by geo-tp** [comment]
I parsed and merged a lot of remotes from flipper irbd, I can't merge the whole database because I'm running out of space.

I consider this completed even if I might add other remotes from flipper later if necessary

See 1.1 releases for more details

**Comment by psifertex** [comment]
Awesome, thanks! Looking forward to checking it out.

**Comment by geo-tp** [comment]
Now this is really completed, full support for the flipper-IRDB

https://github.com/geo-tp/Ultimate-Remote/releases/tag/v1.2
